modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="minerstoolbox"
version="${file.jarVersion}"
displayName="Miner's Toolbox"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="examplemod.png"
credits="ZoNiIC645 for his financial support"
authors="Tictim" #optional
description='''
Actually competent mining explosives.
'''